### ISSUE TITLE
Keep drawer open and custom gestures

### ISSUE THREAD

**Issue by staticdreams** [movielala/TVOSSlideViewController#6]
Nice drawer! I like it a lot.
So I have two questions in one :)
1. Once the drawer is completely open, how do I keep it open and focus on UI elements in it? I intend to have buttons and maybe a table view. Once the select action is down inside the drawer it may close automatically.
2. Would be great to be able to define custom gestures to open the drawer. For instance, in my case, swiping right is not very logical, since I have a large collectionView in my content area and swiping is interfering with collectionView browsing. I was thinking about defining a different gestures to open drawer. (E.g `UIPressType.RightArrow` and `UIPressType.LeftArrow` taps)

**Comment by cemolcay** [comment]
Hi @staticdreams, thank you!

Since TVOSSlideViewController designed for `drag and release` like behaviour, we just focused that feature and its only works with pan gesture on siri remote.

It is kind of hacky but you can try implementing delegate methods of `TVOSSlideViewControllerDelegate` to listen dragging events and you can enable / disable pan gesture by simply calling `disablePanGestureRecognizer` and `enablePanGestureRecognizer` functions of `TVOSSlideViewController` in your delegate implementations. That will give you the opportunity of focusing elements in your drawer. Just don't forget the enabling pan gesture for your slide controller continue working properly.

Also we are always happily open to pull requests!

**Comment by staticdreams** [comment]
Thank you @cemolcay for your response. 
I gathered that TVOSSlideViewController is more of peaking controller, for a quick look behind the scenes. 
I still managed to use it the way I wanted to :)
Eventually I did do a bit of hacking and I had to completely disabled the pan gestures. I assigned `UIPressType.RightArrow` and `UIPressType.LeftArrow` to reproduce steps used when animating the drawer with pan gesture, sans the dragging amount part. It works now! Thank you!
